export const ACTION_TYPES = {
    SIDE_MENU: {
        MD_UP_MENU: 'MD_UP_MENU',
        SM_DOWN_MENU: 'SM_DOWN_MENU'
    },
    LOADING: 'LOADING_PROGRESS',
    SHOPPING_LIST: {
        ADD: 'ADD_SHOPPING_LIST',
        REMOVE: 'REMOVE_SHOPPING_LIST',
        CLEAN: 'CLEAN_SHOPPING_LIST'
    }
};